In [2]:
import numpy as np

In [3]:
ejemplo=np.loadtxt("Ejemplo wiki.txt",dtype=float)

In [4]:
ejemplo

array([[ 1.,  0.,  0.,  0.,  2.],
       [ 0.,  0.,  3.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.]])

In [5]:
np.amax(ejemplo)

3.0

In [7]:
Ejemploporcentaje=(ejemplo*100/np.amax(ejemplo))

In [8]:
Ejemploporcentaje

array([[  33.33333333,    0.        ,    0.        ,    0.        ,
          66.66666667],
       [   0.        ,    0.        ,  100.        ,    0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        ,    0.        ,    0.        ],
       [   0.        ,   66.66666667,    0.        ,    0.        ,    0.        ]])

In [7]:
ejemplo.T

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  2.],
       [ 0.,  3.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 2.,  0.,  0.,  0.]])

In [8]:
U,s,V=np.linalg.svd(ejemplo)
S = np.zeros((4, 5))
S[:4, :4] = np.diag(s)
Vt=np.transpose(V)


In [9]:
U.shape,S.shape,V.shape

((4, 4), (4, 5), (5, 5))

In [10]:
U

array([[ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.],
       [ 0.,  0.,  1.,  0.]])

In [11]:
np.around(S,4)

array([[ 3.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  2.2361,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  2.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ]])

In [12]:
np.around(V,4)

array([[-0.    ,  0.    ,  1.    , -0.    ,  0.    ],
       [ 0.4472, -0.    , -0.    , -0.    ,  0.8944],
       [-0.    ,  1.    ,  0.    , -0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  1.    ,  0.    ],
       [-0.8944,  0.    ,  0.    ,  0.    ,  0.4472]])

In [13]:
B=np.dot(U,np.dot(S,V))

In [14]:
B

array([[ 1.,  0.,  0.,  0.,  2.],
       [ 0.,  0.,  3.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.]])

In [17]:
B1=B.flatten()
print (B1)

[ 1.  0.  0.  0.  2.  0.  0.  3.  0.  0.  0.  0.  0.  0.  0.  0.  2.  0.
  0.  0.]


In [18]:
np.reshape(B1,(4,5))

array([[ 1.,  0.,  0.,  0.,  2.],
       [ 0.,  0.,  3.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.]])