In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
A=np.loadtxt("PruebaSVD2.txt",dtype=float)
print (A)

[[ 1.    1.    1.  ]
 [ 0.    0.25  0.5 ]
 [ 0.    0.75  1.5 ]]


In [4]:
print (np.size(A),A.shape)

9 (3, 3)


In [5]:
U,s,V=np.linalg.svd(A)
assert np.allclose(A,np.dot(U,np.dot(np.diag(s),V)))
s[2:]=0
B=np.dot(U,np.dot(np.diag(s),V))
print (B)
plt.plot(B)
plt.show()

[[  1.00000000e+00   1.00000000e+00   1.00000000e+00]
 [  1.66533454e-16   2.50000000e-01   5.00000000e-01]
 [  4.44089210e-16   7.50000000e-01   1.50000000e+00]]


In [6]:
print (U)

[[ 0.6977309   0.71635995  0.        ]
 [ 0.22653291 -0.22064189 -0.9486833 ]
 [ 0.67959872 -0.66192566  0.31622777]]


In [7]:
print (s)

[ 2.33131543  0.83064336  0.        ]


In [8]:
print (V)

[[ 0.29928636  0.54221027  0.78513419]
 [ 0.8624158   0.19834655 -0.46572271]
 [ 0.40824829 -0.81649658  0.40824829]]
