Henry Steven Rueda Corredor. Rayos-X 


In [2]:
import numpy as np
import numpy.linalg as svd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from numpy.linalg import matrix_rank
import ternary

In [3]:
##Carga el archivo fuente, omite el encabezado y coloca los caracteres como Racionales
Al=np.loadtxt("Al.txt", skiprows= 41, dtype= float)
Na=np.loadtxt("Na.txt", skiprows= 41, dtype= float)
Ca=np.loadtxt("Ca.txt", skiprows= 41, dtype= float)
Fe=np.loadtxt("Fe.txt", skiprows= 41, dtype= float)
Si=np.loadtxt("Si.txt", skiprows= 41, dtype= float)
Mg=np.loadtxt("Mg.txt", skiprows= 41, dtype= float)

In [4]:
## Visualización de la matriz
print (Al)
print (Na)
print (Ca)
print (Fe)
print (Si)
print (Mg)

[[   18.    18.   114. ...,  2171.  2196.  2116.]
 [   24.    91.   139. ...,  1793.  2154.  2131.]
 [   21.    48.   739. ...,  1849.  2042.  2173.]
 ..., 
 [  172.  1782.  2040. ...,    14.    23.    52.]
 [  273.  1779.  2093. ...,     4.     9.    10.]
 [ 1550.  2052.  1936. ...,     4.     4.     6.]]
[[  6.   4.   5. ...,  34.  37.  29.]
 [  9.   7.   5. ...,   7.  29.  30.]
 [  6.   2.   5. ...,  17.  28.  25.]
 ..., 
 [  2.  27.  33. ...,   4.   7.  13.]
 [ 14.  43.  21. ...,   2.   5.   2.]
 [ 48.  38.  26. ...,   2.   2.   1.]]
[[  5.   5.   5. ...,  12.  12.  14.]
 [  5.   6.   4. ...,   6.   8.  12.]
 [  7.   8.   7. ...,  12.  12.   9.]
 ..., 
 [ 14.  15.  13. ...,  13.  14.  10.]
 [ 11.   9.  13. ...,   5.  12.  12.]
 [ 10.   8.  13. ...,  11.  18.  12.]]
[[   9.    8.   26. ...,   52.   43.   32.]
 [   8.   19.   25. ...,  233.   33.   50.]
 [   7.    5.  126. ...,  186.   29.   48.]
 ..., 
 [ 118.   90.   96. ...,    0.    9.   47.]
 [  15.   52.  117. ...,    0.    2. 

In [5]:
Suma=Al+Na+Ca+Fe+Si+Mg
print (Suma)

[[  399.   402.   506. ...,  2487.  2501.  2378.]
 [  420.   501.   543. ...,  2250.  2447.  2432.]
 [  416.   459.  1231. ...,  2279.  2336.  2478.]
 ..., 
 [  463.  1997.  2413. ...,   126.   122.   243.]
 [  569.  2154.  2486. ...,    86.    79.    72.]
 [ 1963.  2367.  2362. ...,   362.   110.    57.]]


In [6]:
## Da el tamaño de la matriz
print (np.size(Al))

568512


In [7]:
## Muestra el numero de filas y columnas de la matriz (fila,columna). Del archivo origen leído como (Line,Step)
tamaño = Al.shape
tamaño2 = Na.shape  
print (tamaño,tamaño2)

(672, 846) (672, 846)


In [8]:
fig=plt.figure(figsize=(14,14))
plt.subplot(331)
plt.imshow(Al)
plt.title('Al')
plt.colorbar(orientation='horizontal')
plt.subplot(332)
plt.imshow(Na)
plt.title('Na')
plt.colorbar(orientation='horizontal')
plt.subplot(333)
plt.imshow(Ca)
plt.title('Ca')
plt.colorbar(orientation='horizontal')
plt.subplot(334)
plt.imshow(Fe)
plt.title('Fe')
plt.colorbar(orientation='horizontal')
plt.subplot(335)
plt.imshow(Si)
plt.title('Si')
plt.colorbar(orientation='horizontal')
plt.subplot(336)
plt.imshow(Mg)
plt.title('Mg')
plt.colorbar(orientation='horizontal')
#plt.show()
plt.savefig('graphs.png')

In [9]:
figure=plt.figure(figsize=(10,10))
imgplot= plt.imshow(Suma,cmap='gray')
plt.colorbar(orientation='horizontal')
plt.title('Compuesta')
plt.savefig('Compuesta.png')

In [10]:
figure=plt.figure(figsize=(10,10))
imgplot2= plt.imshow(Al)
plt.colorbar(orientation='horizontal')
plt.title('Al')
plt.savefig('Al.png')

In [11]:
##Realiza la descomposición de una matriz de datos en un solo vector
Al.flatten()

array([  18.,   18.,  114., ...,    4.,    4.,    6.])

In [12]:
#Convierte todos los arrays en una nueva matriz 
Matriz_de_datos=(np.array([Al.flatten(),Na.flatten(),Ca.flatten(),Fe.flatten(),Si.flatten(),Mg.flatten()])).T
print (Matriz_de_datos)

[[  18.    6.    5.    9.  349.   12.]
 [  18.    4.    5.    8.  354.   13.]
 [ 114.    5.    5.   26.  345.   11.]
 ..., 
 [   4.    2.   11.    2.  329.   14.]
 [   4.    2.   18.    1.   73.   12.]
 [   6.    1.   12.    1.   24.   13.]]


In [13]:
# Se debe saber la dimensión de la matriz nueva para de tal manera crear una nueva matriz para realizar la computación
print (Matriz_de_datos.shape)

(568512, 6)


In [14]:
Matriz_creada= np.loadtxt("Matriz creada.txt", dtype=float).T
print (Matriz_creada)

[[ 1.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0. -1.]
 [ 0.  0.  1. -1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.]
 [ 0.  0.  0.  1.  0.  0.]]


In [15]:
# Multiplicar la Matriz de datos y la creada 
Matriz_mineral=np.dot(Matriz_de_datos,Matriz_creada)
print (Matriz_mineral)
print (Matriz_mineral.shape)

[[  18.    5.    9.    3.  349.  332.]
 [  18.    5.    8.    5.  354.  335.]
 [ 114.    5.   26.  -15.  345.  231.]
 ..., 
 [   4.   11.    2.   12.  329.  316.]
 [   4.   18.    1.   11.   73.   53.]
 [   6.   12.    1.   12.   24.    7.]]
(568512, 6)


In [16]:
#La matriz mineral anterior tiene en primera columna A, segunda C tercera F cuarta Mg y Fe quinta Qz, Sexta Plagioclasa
# Y se debe extraer cada una para devolver al tamaño original de la matriz
A=np.reshape(Matriz_mineral[:,0],Al.shape)
C=np.reshape(Matriz_mineral[:,1],Al.shape)
F=np.reshape(Matriz_mineral[:,2],Al.shape)
Mg_Fe=np.reshape(Matriz_mineral[:,3],Al.shape)
Qz=np.reshape(Matriz_mineral[:,4],Al.shape)
Plg=np.reshape(Matriz_mineral[:,5],Al.shape)

In [17]:
print (A)
print (C)
print (F)
print (Mg_Fe)
print (Qz)
print (Plg)
print (A.shape)

[[   18.    18.   114. ...,  2171.  2196.  2116.]
 [   24.    91.   139. ...,  1793.  2154.  2131.]
 [   21.    48.   739. ...,  1849.  2042.  2173.]
 ..., 
 [  172.  1782.  2040. ...,    14.    23.    52.]
 [  273.  1779.  2093. ...,     4.     9.    10.]
 [ 1550.  2052.  1936. ...,     4.     4.     6.]]
[[  5.   5.   5. ...,  12.  12.  14.]
 [  5.   6.   4. ...,   6.   8.  12.]
 [  7.   8.   7. ...,  12.  12.   9.]
 ..., 
 [ 14.  15.  13. ...,  13.  14.  10.]
 [ 11.   9.  13. ...,   5.  12.  12.]
 [ 10.   8.  13. ...,  11.  18.  12.]]
[[   9.    8.   26. ...,   52.   43.   32.]
 [   8.   19.   25. ...,  233.   33.   50.]
 [   7.    5.  126. ...,  186.   29.   48.]
 ..., 
 [ 118.   90.   96. ...,    0.    9.   47.]
 [  15.   52.  117. ...,    0.    2.    5.]
 [ 153.   50.  200. ...,    2.    1.    1.]]
[[   3.    5.  -15. ...,    0.  -19.  -14.]
 [  -2.  -10.  -22. ..., -161.   23.  -39.]
 [   1.    4. -119. ..., -121.   18.  -35.]
 ..., 
 [-101.  -76.  -76. ...,   14.    3.  -38.]
 

In [17]:
fig=plt.figure(figsize=(14,14))
plt.subplot(331)
plt.imshow(A)
plt.title('A')
plt.colorbar(orientation='horizontal')
plt.subplot(332)
plt.imshow(C)
plt.title('C')
plt.colorbar(orientation='horizontal')
plt.subplot(333)
plt.imshow(F)
plt.title('F')
plt.colorbar(orientation='horizontal')
plt.subplot(334)
plt.imshow(abs(Mg_Fe))
plt.title('Mg_Fe')
plt.colorbar(orientation='horizontal')
plt.subplot(335)
plt.imshow(Qz)
plt.title('Qz')
plt.colorbar(orientation='horizontal')
plt.subplot(336)
plt.imshow(Plg)
plt.title('Plg')
plt.colorbar(orientation='horizontal')
#plt.show()
plt.savefig('Graphs minerals.png')

In [18]:
#Recalcula la matriz A, C y F como porcentaje puntual
Suma_2=(A+C+F)
print (Suma_2)

[[   32.    31.   145. ...,  2235.  2251.  2162.]
 [   37.   116.   168. ...,  2032.  2195.  2193.]
 [   35.    61.   872. ...,  2047.  2083.  2230.]
 ..., 
 [  304.  1887.  2149. ...,    27.    46.   109.]
 [  299.  1840.  2223. ...,     9.    23.    27.]
 [ 1713.  2110.  2149. ...,    17.    23.    19.]]


In [19]:
A_diagrama=np.divide(A*100,Suma_2)
C_diagrama=np.divide(C*100,Suma_2)
F_diagrama=np.divide(F*100,Suma_2)
print (A_diagrama)
print (C_diagrama)
print (F_diagrama)

[[ 56.25        58.06451613  78.62068966 ...,  97.13646532  97.55664149
   97.87234043]
 [ 64.86486486  78.44827586  82.73809524 ...,  88.23818898  98.13211845
   97.17282262]
 [ 60.          78.68852459  84.74770642 ...,  90.32730826  98.03168507
   97.44394619]
 ..., 
 [ 56.57894737  94.43561208  94.92787343 ...,  51.85185185  50.
   47.70642202]
 [ 91.30434783  96.68478261  94.15204678 ...,  44.44444444  39.13043478
   37.03703704]
 [ 90.48453006  97.25118483  90.08841322 ...,  23.52941176  17.39130435
   31.57894737]]
[[ 15.625       16.12903226   3.44827586 ...,   0.53691275   0.5330964
    0.64754857]
 [ 13.51351351   5.17241379   2.38095238 ...,   0.29527559   0.36446469
    0.54719562]
 [ 20.          13.1147541    0.80275229 ...,   0.58622374   0.57609217
    0.40358744]
 ..., 
 [  4.60526316   0.79491256   0.60493253 ...,  48.14814815  30.43478261
    9.17431193]
 [  3.67892977   0.48913043   0.58479532 ...,  55.55555556  52.17391304
   44.44444444]
 [  0.58377116   0.3791469

In [20]:
Matriz_ACF=(np.array([F_diagrama.flatten(),A_diagrama.flatten(),C_diagrama.flatten()])).T
print (Matriz_ACF)
print (Matriz_ACF.shape)

[[ 28.125       56.25        15.625     ]
 [ 25.80645161  58.06451613  16.12903226]
 [ 17.93103448  78.62068966   3.44827586]
 ..., 
 [ 11.76470588  23.52941176  64.70588235]
 [  4.34782609  17.39130435  78.26086957]
 [  5.26315789  31.57894737  63.15789474]]
(568512, 3)


In [21]:
#Ternary diagram, cabe aclarar que para la matriz los datos deben ser puestos como FAC
scale = 100
figure, tax = ternary.figure(scale=scale,)
fontsize=20
tax.set_title("ACF", fontsize=fontsize)
tax.left_axis_label("C",fontsize=fontsize, position=(-0.01,0.05,0),rotation=0)
tax.right_axis_label("A", fontsize=fontsize, position=(-0.06,1.12,0),rotation=0)
tax.bottom_axis_label("F", fontsize=fontsize, position=(0.93,0.05,0))
tax.boundary(linewidth=2.0)
tax.gridlines(multiple=10, color="blue")
tax.scatter(Matriz_ACF,color='purple', label='Qz, Mg y Fe, Plagioclasa', s=0.2)
tax.legend()
tax.ticks(axis='lbr', linewidth=1, multiple=10, clockwise=True)
#tax.show()
plt.savefig('ACF.png')

Cálculo del Single Value Decomposition

In [22]:
Matriz_ACF.shape

(568512, 3)

In [18]:
U,s,V=np.linalg.svd(A)
S = np.zeros((A.shape))
Vt=np.transpose(V)
S[:672, :672] = np.diag(s)

In [19]:
U1,s1,V1=np.linalg.svd(C)
S1 = np.zeros((C.shape))
Vt1=np.transpose(V1)
S1[:672, :672] = np.diag(s1)

In [20]:
U2,s2,V2=np.linalg.svd(F)
S2 = np.zeros((F.shape))
Vt2=np.transpose(V2)
S2[:672, :672] = np.diag(s2)