# Reconstrucción del svd de Fischer

In [1]:
import numpy as np
import numpy.linalg as svd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
%pylab inline

Populating the interactive namespace from numpy and matplotlib


`%matplotlib` prevents importing * from pylab and numpy


In [2]:
A=np.loadtxt("SVDfischer.txt",dtype=float)
print (A)
A.shape

[[ 1.     1.     1.     1.     1.   ]
 [ 0.     0.5    0.8    0.45   0.7  ]
 [ 0.     0.475  1.14   0.523  1.235]
 [ 0.     0.025  0.06   0.027  0.065]]


(4, 5)

In [3]:
U,s,V=np.linalg.svd(A)
S = np.zeros(A.shape)
Vt=np.transpose(V)
S[:4, :4] = np.diag(s)


In [4]:
print ((U.shape),(S.shape), (Vt.shape))
A.shape

(4, 4) (4, 5) (5, 5)


(4, 5)

In [14]:
np.around(U,3)

array([[ 0.712,  0.697, -0.083,  0.   ],
       [ 0.404, -0.31 ,  0.861,  0.001],
       [ 0.573, -0.646, -0.502, -0.053],
       [ 0.03 , -0.034, -0.027,  0.999]])

In [22]:
np.around(S,3)

array([[ 3.018,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.88 ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.178,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ]])

In [16]:
np.around(Vt,3)

array([[ 0.236,  0.792, -0.465,  0.214, -0.236],
       [ 0.393,  0.266,  0.609,  0.426,  0.471],
       [ 0.56 , -0.329,  0.18 ,  0.213, -0.707],
       [ 0.396,  0.248,  0.232, -0.853, -0.   ],
       [ 0.565, -0.364, -0.571,  0.001,  0.471]])

In [17]:
B=np.dot(U,np.dot(S,V))

In [18]:
np.around(B,5)

array([[ 1.   ,  1.   ,  1.   ,  1.   ,  1.   ],
       [ 0.   ,  0.5  ,  0.8  ,  0.45 ,  0.7  ],
       [ 0.   ,  0.475,  1.14 ,  0.523,  1.235],
       [ 0.   ,  0.025,  0.06 ,  0.027,  0.065]])

In [19]:
#Se deben extraer las dos últimas columnas de la matriz de V dado que S contiene en estas dos columnas de ceros
#Matemáticamente es extraer el rank de la matriz
# El número de términos en la diagonall de S diferentes de 0 es el rango de A

In [20]:
V4=[row[3] for row in Vt]
V5=[row[4] for row in Vt]

In [12]:
np.around(V4,3)

array([ 0.214,  0.426,  0.213, -0.853,  0.001])

In [13]:
np.around(V5,3)

array([-0.236,  0.471, -0.707, -0.   ,  0.471])