Henry Steven Rueda Corredor. Rayos-X 


In [1]:
import numpy as np
import numpy.linalg as svd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import ternary
from numpy.linalg import matrix_rank

In [2]:
##Carga el archivo fuente, omite el encabezado y coloca los caracteres como Racionales
Al=np.loadtxt("Al.txt", skiprows= 41, dtype=float)
Na=np.loadtxt("Na.txt", skiprows= 41, dtype= float)
Ca=np.loadtxt("Ca.txt", skiprows= 41, dtype= float)
Fe=np.loadtxt("Fe.txt", skiprows= 41, dtype= float)
Si=np.loadtxt("Si.txt", skiprows= 41, dtype= float)
Mg=np.loadtxt("Mg.txt", skiprows= 41, dtype= float)
Ba=np.loadtxt("Ba.txt", skiprows= 41, dtype= float)
K=np.loadtxt("K.txt", skiprows= 41, dtype= float)

In [3]:
## Visualización de la matriz
print (Al)
print (Na)
print (Ca)
print (Fe)
print (Si)
print (Mg)
print (Ba)
print (K)

[[  191.   139.   244. ...,  1063.  1047.  1088.]
 [  126.   130.   122. ...,  1072.  1056.  1016.]
 [  115.   133.    98. ...,  1042.  1034.  1076.]
 ..., 
 [  124.   127.   122. ...,   130.   127.   137.]
 [  115.   115.   116. ...,   125.   136.   129.]
 [    0.     0.     0. ...,     0.     0.     0.]]
[[   4.   21.  125. ...,  140.  110.  111.]
 [   7.    8.   45. ...,  104.  100.  131.]
 [   5.    6.    6. ...,  129.  104.  102.]
 ..., 
 [   7.    5.    3. ...,    4.    5.    3.]
 [   6.    5.    5. ...,    4.    7.    5.]
 [   4.    2.    4. ...,    2.    5.    3.]]
[[ 37.  29.  45. ...,  45.  70.  57.]
 [ 35.  42.  29. ...,  57.  50.  49.]
 [ 41.  47.  36. ...,  65.  76.  69.]
 ..., 
 [ 36.  41.  31. ...,  41.  34.  39.]
 [ 40.  39.  42. ...,  32.  28.  32.]
 [  0.   0.   0. ...,   0.   0.   0.]]
[[  1.   4.   7. ...,  13.   9.  13.]
 [  1.   3.   7. ...,   9.  15.  11.]
 [  0.   2.   2. ...,  14.  18.  13.]
 ..., 
 [  3.   1.   3. ...,   1.   1.   1.]
 [  2.   1.   1. ...,   0

In [4]:
Suma=Al+Na+Ca+Fe+Si+Mg+Ba+K
print (Suma)

[[ 2902.  2954.  3059. ...,  2856.  2882.  2851.]
 [ 2902.  2962.  2902. ...,  2835.  2841.  2828.]
 [ 2921.  2926.  2923. ...,  2872.  2866.  2902.]
 ..., 
 [ 2946.  2949.  2925. ...,  2911.  2969.  2923.]
 [ 2921.  2894.  2947. ...,  2971.  2938.  2926.]
 [   14.    16.    14. ...,    15.    16.    19.]]


In [5]:
## Da el tamaño de la matriz 
print (np.size(Al))
print (Al.shape)

577600
(760, 760)


In [6]:
fig=plt.figure(figsize=(14,14))
plt.subplot(331)
plt.imshow(Al,cmap='gist_rainbow_r')
plt.title('Al')
plt.colorbar(orientation='horizontal')
plt.subplot(332)
plt.imshow(Na,cmap='gist_rainbow_r')
plt.title('Na')
plt.colorbar(orientation='horizontal')
plt.subplot(333)
plt.imshow(Ca,cmap='gist_rainbow_r')
plt.title('Ca')
plt.colorbar(orientation='horizontal')
plt.subplot(334)
plt.imshow(Fe,cmap='gist_rainbow_r')
plt.title('Fe')
plt.colorbar(orientation='horizontal')
plt.subplot(335)
plt.imshow(Si,cmap='gist_rainbow_r')
plt.title('Si')
plt.colorbar(orientation='horizontal')
plt.subplot(336)
plt.imshow(Mg,cmap='gist_rainbow_r')
plt.title('Mg')
plt.colorbar(orientation='horizontal')
plt.subplot(337)
plt.imshow(Ba,cmap='gist_rainbow_r')
plt.title('Ba')
plt.colorbar(orientation='horizontal')
plt.subplot(338)
plt.imshow(K,cmap='gist_rainbow_r')
plt.title('K')
plt.colorbar(orientation='horizontal')
#plt.show()
plt.savefig('graficas.png')


In [7]:
figure=plt.figure(figsize=(10,10))
imgplot= plt.imshow(Suma,cmap='gray_r')
plt.colorbar(orientation='horizontal')
plt.title('Compuesta')
plt.savefig('Compuesta.png')

In [8]:
figure=plt.figure(figsize=(10,10))
imgplot2= plt.imshow(K,cmap='gist_rainbow_r')
plt.colorbar(orientation='horizontal')
plt.title('K')
plt.savefig('K.png')

In [9]:
Knorm=np.loadtxt("K.txt", skiprows= 41, dtype=float)
K.max(), K.min ()
vmax=400
vmin = 200
Knorm[Knorm > vmax] = np.nan
Knorm[Knorm< vmin] = np.nan
my_cmap = plt.cm.get_cmap()
my_cmap.set_under('w')
plt.imshow(Suma,cmap='gray')
plt.imshow(Knorm,cmap=my_cmap, interpolation='none',vmin=0.01)
plt.title('K')
plt.savefig('Knorm.png')

C:\Users\Nataly\Anaconda3\lib\site-packages\ipykernel\__main__.py:6: RuntimeWarning: invalid value encountered in less


In [10]:
figure=plt.figure(figsize=(10,10))
plt.imshow(Ba,cmap='gist_rainbow_r')
plt.colorbar(orientation='horizontal')
plt.title('Ba')
plt.savefig('Ba.png')

In [11]:
Banorm=np.loadtxt("Ba.txt", skiprows= 41, dtype=float)
vmax=320
vmin= 24
Banorm[Banorm > vmax] = np.nan
Banorm[Banorm< vmin] = np.nan
my_cmap = plt.cm.get_cmap()
my_cmap.set_under('w')
plt.imshow(Suma,cmap='gray')
plt.imshow(Banorm,cmap=my_cmap, interpolation='none',vmin=0.01)
plt.title('Ba')
plt.savefig('Banorm.png')

C:\Users\Nataly\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: RuntimeWarning: invalid value encountered in less


In [12]:
##Realiza la descomposición de una matriz de datos en un solo vector
Al.flatten()

array([ 191.,  139.,  244., ...,    0.,    0.,    0.])

In [13]:
#Convierte todos los arrays en una nueva matriz 
Matriz_de_datos=(np.array([Al.flatten(),Na.flatten(),Ca.flatten(),Fe.flatten(),Si.flatten(),Mg.flatten(),Ba.flatten(),K.flatten()])).T
print (Matriz_de_datos)

[[ 191.    4.   37. ...,   98.   13.   82.]
 [ 139.   21.   29. ...,  102.   22.   79.]
 [ 244.  125.   45. ...,   94.   64.   86.]
 ..., 
 [   0.    2.    0. ...,    0.   10.    0.]
 [   0.    5.    0. ...,    0.    6.    0.]
 [   0.    3.    0. ...,    0.   14.    0.]]


In [14]:
# Se debe saber la dimensión de la matriz nueva creada para de tal manera crear una nueva matriz para realizar la computación
print (Matriz_de_datos.shape)

(577600, 8)


In [15]:
Matriz_creada= np.loadtxt("Matriz creada.txt", dtype=float)
print (Matriz_creada)

[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [-1.  1. -1.  0.  1.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  0. -1.  0. -1.  1.]]


In [16]:
# Multiplicar la Matriz de datos y la creada 
Matriz_mineral=np.dot(Matriz_de_datos,Matriz_creada)
print (Matriz_mineral)
print (Matriz_mineral.shape)

[[ 175.   85.  -94. ...,    1.  -69.   82.]
 [ 116.   80.  -81. ...,    4.  -57.   79.]
 [ 236.   30.   31. ...,    7.  -22.   86.]
 ..., 
 [   0.  -10.    2. ...,    3.   10.    0.]
 [   0.   -6.    5. ...,    5.    6.    0.]
 [   0.  -14.    3. ...,    2.   14.    0.]]
(577600, 8)


In [17]:
#La matriz mineral anterior tiene en primera columna A, segunda C tercera F cuarta Mg y Fe quinta Qz, Sexta Plagioclasa
# Y se debe extraer cada una para devolver al tamaño original de la matriz
A=np.reshape(Matriz_mineral[:,0],Al.shape)
C=np.reshape(Matriz_mineral[:,1],Al.shape)
F=np.reshape(Matriz_mineral[:,2],Al.shape)
Mg_Fe=np.reshape(Matriz_mineral[:,3],Al.shape)
Qz=np.reshape(Matriz_mineral[:,4],Al.shape)
Plg=np.reshape(Matriz_mineral[:,5],Al.shape)
KNa=np.reshape(Matriz_mineral[:,6],Al.shape)
BaAlSiK=np.reshape(Matriz_mineral[:,7],Al.shape)

In [18]:
print (A)
print (C)
print (F)
print (Mg_Fe)
print (Qz)
print (Plg)
print (KNa)
print (BaAlSiK)
print (A.shape)

[[  175.   116.   236. ...,  1167.  1130.  1203.]
 [  112.   115.   110. ...,  1172.  1193.  1139.]
 [  118.   136.   102. ...,  1147.  1134.  1179.]
 ..., 
 [  117.   114.   122. ...,   143.   133.   132.]
 [  102.   110.    94. ...,   126.   133.   110.]
 [    0.     0.     0. ...,     0.     0.     0.]]
[[ 85.  80.  30. ...,  42.  42.  32.]
 [ 83.  80.  76. ...,  48.  39.  61.]
 [ 72.  67.  79. ...,  69.  67.  76.]
 ..., 
 [ 73.  88.  71. ...,  56.  61.  83.]
 [ 82.  72.  93. ...,  70.  75.  77.]
 [ -9. -13.  -7. ..., -10.  -6. -14.]]
[[-94. -81.  31. ...,  -5. -45. -39.]
 [-84. -78. -51. ..., -45. -56. -25.]
 [-80. -71. -87. ..., -26. -67. -60.]
 ..., 
 [-84. -93. -81. ..., -69. -70. -92.]
 [-85. -75. -98. ..., -81. -78. -89.]
 [  4.   2.   4. ...,   2.   5.   3.]]
[[ 36.  25.  38. ...,  32.  61.  44.]
 [ 34.  39.  22. ...,  48.  35.  38.]
 [ 41.  45.  34. ...,  51.  58.  56.]
 ..., 
 [ 33.  40.  28. ...,  40.  33.  38.]
 [ 38.  38.  41. ...,  32.  28.  29.]
 [ -1.  -1.  -3. ...,  

In [19]:
Suma_2=(A+C+F)
A_diagrama=np.divide(A*100,Suma_2)
C_diagrama=np.divide(C*100,Suma_2)
F_diagrama=np.divide(F*100,Suma_2)
Matriz_ACF=(np.array([F_diagrama.flatten(),A_diagrama.flatten(),C_diagrama.flatten()])).T
print (Matriz_ACF)
print (Matriz_ACF.shape)

[[ -56.62650602  105.42168675   51.20481928]
 [ -70.43478261  100.86956522   69.56521739]
 [  10.43771044   79.46127946   10.1010101 ]
 ..., 
 [ -25.           -0.          125.        ]
 [-500.           -0.          600.        ]
 [ -27.27272727   -0.          127.27272727]]
(577600, 3)


C:\Users\Nataly\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: divide by zero encountered in true_divide
  from ipykernel import kernelapp as app
C:\Users\Nataly\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app
C:\Users\Nataly\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: RuntimeWarning: divide by zero encountered in true_divide
  app.launch_new_instance()
C:\Users\Nataly\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: RuntimeWarning: divide by zero encountered in true_divide


In [1]:
#Ternary diagram, cabe aclarar que para la matriz los datos deben ser puestos como FAC
scale = 100
figure, tax = ternary.figure(scale=scale,)
fontsize=20
tax.set_title("ACF", fontsize=fontsize)
tax.left_axis_label("C",fontsize=fontsize, position=(-0.01,0.05,0),rotation=0)
tax.right_axis_label("A", fontsize=fontsize, position=(-0.06,1.12,0),rotation=0)
tax.bottom_axis_label("F", fontsize=fontsize, position=(0.93,0.05,0))
tax.boundary(linewidth=2.0)
tax.gridlines(multiple=10, color="blue")
tax.scatter(Matriz_ACF,color='purple', label='Qz, Mg y Fe, Plagioclasa', s=0.2)
tax.legend()
tax.ticks(axis='lbr', linewidth=1, multiple=10, clockwise=True)
#tax.show()
plt.savefig('ACF.png')

NameError: name 'ternary' is not defined

Cálculo del Single Value Decomposition